services:
  - type: web
    plan: free
    name: Sharingan-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/dakshkohli23/Sharingan-Rename-Bot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DB_NAME 
        sync: false
      - key: DB_URL 
        sync: false 
      - key: START_PIC 
        sync: false
      - key: ADMIN 
        sync: false    
    autoDeploy: false 
